<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_SVIL/CPQProject/BS_SQL_TIBCO_CHECK_ORDER_VALIDATION" name="BS_SQL_TIBCO_CHECK_ORDER_VALIDATION-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="BS_SQL_TIBCO_CHECK_ORDER_VALIDATION.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_SVIL/CPQProject/BS_SQL_TIBCO_CHECK_ORDER_VALIDATION"/>
    <wsdl:binding name="BS_SQL_TIBCO_CHECK_ORDER_VALIDATION_ptt-binding" type="bs:BS_SQL_TIBCO_CHECK_ORDER_VALIDATION_ptt" xmlns:bs="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_SVIL/CPQProject/BS_SQL_TIBCO_CHECK_ORDER_VALIDATION">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BS_SQL_TIBCO_CHECK_ORDER_VALIDATION">
            <soap:operation soapAction="BS_SQL_TIBCO_CHECK_ORDER_VALIDATION"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="BS_SQL_TIBCO_CHECK_ORDER_VALIDATION.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_SVIL/CPQProject/BS_SQL_TIBCO_CHECK_ORDER_VALIDATION">
            <con:wsdl ref="CPQProject/Resources/BS_SQL_TIBCO_CHECK_ORDER_VALIDATION"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/OSB_SVIL/CPQProject/BS_SQL_TIBCO_CHECK_ORDER_VALIDATION</con:targetNamespace>
</con:wsdlEntry>